File name generator
OpenTechStrategies/permanent-rclone-qa pull request #2
Opened 2023-02-24 18:05 UTC by mithuna

This will generate test file names that can be used to upload files with  a variety of file names.

2023-02-24 18:38 UTC, Fenn-CS requested changes
This looks like a great start. A few comments here:

1. We don't seem to do anything with `craft_filenames` (Running the script generates the file name and does nothing with them not even print them out, Ideally we want to print write the to disk in a single file or as multiple files, minimally we should at least print out the results for easy copy-and-use)

2. It appears the script would always put the `input_characters` in the same spot, namely the white space which you left in the middle of `"new file"`. At the end it results in testing the same class of files, you probably want to use `random()` to guess a position between 0 and the length  [`len()`]of the filename. That way, weird characters would be inserted in multiple places.

For context this are the results of me running it with an added print statement

```
['new-file', 'new/file', 'new?file', 'new@file', 'new!file', 'new*file', 'new#file', 'new%file', 'new&file', 'new{file', 'new}file', 'new<file', 'new>file', 'new file', 'new$file', 'new!file', 'new:file', 'new+file', 'new`file', 'new|file', 'new=file', 'new123file', 'new\\file', "new'file"]
```

3. Following the same logic above, weird characters must not appear in every file name, some file names could be simple. You can use random to decide that but this is just a nice to have. 

4. You can also use something like https://pypi.org/project/Random-Word/ anything of that nature to suggest new words which you can play with and insert characters in random positions. The advantage of this is that, every generated file won't have the "new file" words in it, it could be any combination of words.

5. You probably want to add a prefix or something to every resulting name that by simple observation we can know that it was a filename we generated. Such as `generated-XXXresult-of-your-algo`

6. Perhaps, we should be able to decide how many files names it would generate.

Finally, I left some formatting suggestions which you can easily wipe out and avoid in the future by running `flake8` on your file locally.

2023-02-24 18:38 UTC, Fenn-CS commented on testTree.py
> +    def craft_filenames(input_characters,file_name_raw):
`def craft_filenames(input_characters, file_name_raw):`

2023-02-24 18:38 UTC, Fenn-CS commented on testTree.py
> +        craft_filenames(input_characters = input_characters ,file_name_raw = file_name_raw)
`craft_filenames(input_characters = input_characters, file_name_raw = file_name_raw)`

2023-02-24 19:39 UTC, kfogel commented
I'm about to start a review, but one quick comment in response to [@Fenn-CS's comment above](https://github.com/OpenTechStrategies/permanent-rclone-qa/pull/2#pullrequestreview-1314057155):

We don't want any randomness from one run to the next, we want predictability.  Using `new file` or whatever as the consistent basis for the filenames is fine.  We don't need to test special characters in random positions; we just need to test them at beginning, somewhere in the middle, and at the end of the name.

2023-02-24 19:54 UTC, kfogel requested changes

2023-02-24 19:54 UTC, kfogel commented on testTree.py
> +    def craft_filenames(input_characters,file_name_raw):
* We don't need a class (not yet, at any rate).  The fact that the class is not  referred to anywhere in the code is a sign that you don't need the class :-).  I.e., we don't create an instance of directoryTree() anywhere.

* For Python classes, use upper-case initial characters -- i.e., "DirectoryTree", not "directoryTree".  (See [PEP 8](https://peps.python.org/pep-0008/#class-names) for reference.)  That doesn't matter here because we don't need a class anyway; I'm just letting you know for your future Python coding.  The Java convention of lowerThenUpper is not used in Python-land.

* For functions and methods (a "method" is just a function that is part of a class definition and that operates on an instance of that class), "lower_case_with_underscores" is fine.

* For functions you define (or classes you define, for that matter) always write a documentation string explaining what the function does, what input parameters it takes, what value(s) it returns, and what special exceptions it might throw.  (There can be exceptions for very conventional methods, like `__init__()` and `__str__()` in a class, but don't worry about those for now.)  For some example code that has lots of doc strings, see [here](https://code.librehq.com/ots/ots-tools/-/blob/main/find-dups) (or any of the other Python programs in that repository).

2023-02-24 19:54 UTC, kfogel commented on testTree.py
> +        for j in range(len(input_characters)):
`for j in input_characters:`

You can just iterate across a list or a tuple directly, one element at a time.  You don't need to generate a bunch of index values with range() and then use each index; Python gives you iteration support directly :-).

2023-02-24 19:54 UTC, kfogel commented on testTree.py
> +                if(file_name_raw)[i] == ' ':
If you were going to do it this way, you could use the `.find()` method on strings (read about it in the Python docs) to find where the space is.

But instead, why not just maintain two variables, `filename_front` and `filename_back`, with values "new" and "file" respectively, and then just assemble any filename you want using string concatenation?  Like `filename_front + special_character + filename_back`.

2023-02-24 19:54 UTC, kfogel commented on testTree.py
> +        craft_filenames(input_characters = input_characters ,file_name_raw = file_name_raw)
* You don't need to name the parameters; you can just call the function with positional parameters: craft_filenames(input_characters, file_name_raw).  But, again, without a documentation string on the function, I don't actually know what `craft_filenames()` is *intended* to do, so it's hard for me to evaluate whether it is doing what it is intended to do.

* We have to actually create the files on disk somewhere :-).

2023-02-24 20:14 UTC, mithuna commented on testTree.py
> +                if(file_name_raw)[i] == ' ':
I like that and makes in simpler. I can use the same to find files names with special characters in the  beginning, and at the end. I will rewrite the code.

2023-02-24 20:16 UTC, mithuna commented on testTree.py
> +        craft_filenames(input_characters = input_characters ,file_name_raw = file_name_raw)
Oh yes. I tried that and the IDE was complaining. Now I know it was because of the lacking documentation string.

2023-02-27 13:46 UTC, Fenn-CS reviewed
This looks simple and okay! According the requirements that Karl noted in the last review I think it does the job except of one thing (Not writing the file anywhere on disk)?

- I see there's a `testfile.txt` which is not used anywhere in the code, I am not sure what it is for BUT you can add a folder `generatedFiles` that is tracked but whose content is not tracked. In that folder, for every name generated, you simply copy contents of `testfile.txt` to a file with the new-name you generated.

*Questions*

- Do extensions not matter here? (I thought ideally a bunch of files with various extensions and structures would be nice to have as well for QA cc : @kfogel )

2023-02-27 14:55 UTC, mithuna commented on testTree.php
> +   $addMiEndCharacter = $filenameFirst.$filenameSecond.$inputCharacter;
Oh thanks for catching that.

2023-02-27 17:10 UTC, kfogel commented
@Fenn-CS To answer your question: we care about extensions eventually, but one thing at a time: first let's just get a tree generated on disk.

2023-02-27 17:11 UTC, mithuna commented
> This looks simple and okay! According the requirements that Karl noted in the last review I think it does the job except of one thing (Not writing the file anywhere on disk)?
> 
> * I see there's a `testfile.txt` which is not used anywhere in the code, I am not sure what it is for BUT you can add a folder `generatedFiles` that is tracked but whose content is not tracked. In that folder, for every name generated, you simply copy contents of `testfile.txt` to a file with the new-name you generated.
> 
> _Questions_
> 
> * Do extensions not matter here? (I thought ideally a bunch of files with various extensions and structures would be nice to have as well for QA cc : @kfogel )

I was asked to create a test tree. I am starting a thread in Zulip to understand more.

2023-02-27 19:05 UTC, merged